language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - build-essential
    - gawk
    - ccache
    - genromfs
    - libc6-i386
    - libxml2-dev
    - libxslt1-dev
    - python-pip
    - python-dev
    - zlib1g-dev
    - gcc-4.9
    - g++-4.9
    - cmake
    - cmake-data
cache:
  ccache: true
  directories:
  - "$HOME/opt"
before_install:
- Tools/scripts/configure-ci.sh
- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then export CI_CRON_JOB=1 ; fi
script:
- python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle APMrover2
- python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle AntennaTracker
- python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle ArduCopter
- python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle ArduPlane
- python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle ArduSub
- Tools/scripts/build_ci.sh
before_cache:
- ccache -z
notifications:
  slack:
    secure: f4U59lBQI1uV9DRrPPnUpKMYWFas8njpZHRF5NIMmCyD0D6ptnY3PwmZZNVGeIqRT0t6enh5nJVaoq3wmMOWzAWNRi8ky6Xr8edOdGwH5qgRW3GreJdvKtMLBG7x3kFGMSCN10m9Kz3+7lIZWgK4ncfuHMgjz2Jiqgx09xULU6jttRYKU6VftjxcejAYU6O80gu/vCVNwPTQtbhXDssVRcZWPXYfZ3EnkuL8/dyc6RAiD9nYo886mnzOiccXvGrH6BMs3bXy2R1TEtM0gEajeKWtzdyBHBuBX4QOt2LSJNBu4/p1oi8fa1gyMd4ETGcJSgP0gHAidf6kE7A3OxgMgwQldPrWthb7hhwX8gxuXRGv7qFJbuFRtrz/kFC9vO4uTuk/eY62/lAeeDCXQzy4Zw5OyUjQ5uBs5pV/PC/4UhH0ZZ+1mxAKyhAWZCELagQ9wqwd1iad7ZJpAot1ymH4JgfkP4YAoItlb5+ZJYVSv7s8NwmzjJw8YxcBkSyl7HHnxGjK27gwRJmS8T/GA4QKlkxkMZiz47q+HEKD4K9Amz3bEZ4MHe+7xU8aYktg/R8XULWKLtS7D0/ZTi//TaqzOnpSrbJdM7WPlK6ofIfb0SXFb2tzLPXykXejC5AnWVP9dRIPKoYVJLM8wPVRfVH0nip4ZKxdoI1W5ViAq2Wda38=
compiler:
- gcc
env: 
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env: CI_BUILD_TARGET="px4-v2"
  - compiler: gcc
    env: CI_BUILD_TARGET="sitltest"
